### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by martin-braun** [deltadaedalus/vudu#1]
I get the error "Could not open file lib.vudu/inconsolata-Regular.ttf. Does not exist.", because I want to put your lib into a lib subfolder and it seems to use that require string to get the new font.

It will probably also make problems when loading other files. I will move it to the root, although I wish this to be working in sub directories, too. 

Thank you.

**Comment by deltadaedalus** [comment]
On it man!  I didn't follow standard conventions for Lua packages, I'll put out a hotfix addressing this as soon as I can.  For anybody else experiencing this issue, another workaround would be to require it as "lib/vudu".

**Comment by deltadaedalus** [comment]
Updated the way vudu is imported in version 0.2.0 to fit better with convention.
