### ISSUE TITLE
vudu crashes when hotkey is pressed in function.love.keypressed() despite vudu.hook()

### ISSUE THREAD

**Issue by todistantlands** [deltadaedalus/vudu#12]
Sorry for the verbose title.

I'm trying out Vudu but finding it disagrees with how I'm handling input. I'm using love.keypressed() to register when the spacebar is pressed. While this code is in the project, pressing the ""`"" key causes Love2D to crash (no error message, just closes).

This exact code causes the error for me without fail:

```lua
vudu = require "vudu"

function love.load()
    vudu.initialize()
end

function love.update(dt)
    -- do stuff
end

function love.keypressed(key, scancode, isRepeat)
    vudu.hook()
    if scancode == "space" then
        --do other stuff
    end
end

function love.draw()
    -- draw stuff
end
```
The outcome is the same with vudu.hook() at the end of the love.keypressed() callback. 

Any help much appreciated.

**Comment by deltadaedalus** [comment]
vudu.hook only needs to be used if the value of the love.keypressed function changes at runtime.  If you remove your call to vudu.hook, you should be good to go!
